# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Email.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_emailMainWindow(object):
    def setupUi(self, emailMainWindow):
        emailMainWindow.setObjectName("emailMainWindow")
        emailMainWindow.resize(1080, 1920)
        self.centralwidget = QtWidgets.QWidget(emailMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundLabel = QtWidgets.QLabel(self.centralwidget)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 1080, 1920))
        self.backgroundLabel.setStyleSheet("background-color: #30363A")
        self.backgroundLabel.setText("")
        self.backgroundLabel.setPixmap(QtGui.QPixmap("design/assets/EmailBackground.png"))
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.headerLabel = QtWidgets.QLabel(self.centralwidget)
        self.headerLabel.setGeometry(QtCore.QRect(0, 0, 1080, 189))
        self.headerLabel.setPixmap(QtGui.QPixmap("design/assets/Header.png"))
        self.headerLabel.setObjectName("headerLabel")
        self.sendEmailButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendEmailButton.setGeometry(QtCore.QRect(347, 1215, 386, 108))
        self.sendEmailButton.setStyleSheet("background-image: url(design/assets/EmailSendButton.png);\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.sendEmailButton.setText("")
        self.sendEmailButton.setObjectName("sendEmailButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(186, 925, 708, 48))
        self.label.setStyleSheet("font-family: TacticSans-Reg;\n"
"font-size: 40px;\n"
"color: #FFFFFF;")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(101, 1463, 82, 50))
        self.pushButton.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 1463, 82, 50))
        self.pushButton_2.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(278, 1463, 82, 50))
        self.pushButton_3.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(366, 1463, 82, 50))
        self.pushButton_4.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(454, 1463, 82, 50))
        self.pushButton_5.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(898, 1463, 82, 50))
        self.pushButton_6.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(545, 1463, 82, 50))
        self.pushButton_7.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(810, 1463, 82, 50))
        self.pushButton_8.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(634, 1463, 82, 50))
        self.pushButton_9.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(722, 1463, 82, 50))
        self.pushButton_10.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(57, 1520, 82, 82))
        self.pushButton_11.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(145, 1520, 82, 82))
        self.pushButton_12.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(233, 1520, 82, 82))
        self.pushButton_13.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(321, 1520, 82, 82))
        self.pushButton_14.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(410, 1520, 82, 82))
        self.pushButton_15.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(498, 1520, 82, 82))
        self.pushButton_16.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(854, 1520, 82, 82))
        self.pushButton_17.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(766, 1520, 82, 82))
        self.pushButton_18.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(943, 1520, 82, 82))
        self.pushButton_19.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(590, 1520, 82, 82))
        self.pushButton_21.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(678, 1520, 82, 82))
        self.pushButton_22.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.shiftButton = QtWidgets.QPushButton(self.centralwidget)
        self.shiftButton.setGeometry(QtCore.QRect(943, 1610, 82, 82))
        self.shiftButton.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);\n"
"background-image: url(design/assets/Shift.png);")
        self.shiftButton.setText("")
        self.shiftButton.setObjectName("shiftButton")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(321, 1610, 82, 82))
        self.pushButton_23.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(233, 1610, 82, 82))
        self.pushButton_24.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(766, 1610, 82, 82))
        self.pushButton_25.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(854, 1610, 82, 82))
        self.pushButton_26.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(678, 1610, 82, 82))
        self.pushButton_27.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(410, 1610, 82, 82))
        self.pushButton_28.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(57, 1610, 82, 82))
        self.pushButton_29.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(498, 1610, 82, 82))
        self.pushButton_30.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(590, 1610, 82, 82))
        self.pushButton_31.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_32.setGeometry(QtCore.QRect(145, 1610, 82, 82))
        self.pushButton_32.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(320, 1701, 82, 82))
        self.pushButton_20.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_33.setGeometry(QtCore.QRect(232, 1701, 82, 82))
        self.pushButton_33.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_34.setGeometry(QtCore.QRect(765, 1701, 82, 82))
        self.pushButton_34.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_35.setGeometry(QtCore.QRect(677, 1701, 82, 82))
        self.pushButton_35.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_36.setGeometry(QtCore.QRect(409, 1701, 82, 82))
        self.pushButton_36.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_37.setGeometry(QtCore.QRect(589, 1701, 82, 82))
        self.pushButton_37.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_38.setGeometry(QtCore.QRect(497, 1701, 82, 82))
        self.pushButton_38.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_39.setGeometry(QtCore.QRect(56, 1701, 82, 82))
        self.pushButton_39.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_40.setGeometry(QtCore.QRect(144, 1701, 82, 82))
        self.pushButton_40.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.pushButton_40.setObjectName("pushButton_40")
        self.backspaceButton = QtWidgets.QPushButton(self.centralwidget)
        self.backspaceButton.setGeometry(QtCore.QRect(855, 1701, 170, 82))
        self.backspaceButton.setStyleSheet("background-color: #484E53;\n"
"font-family: Calibri;\n"
"font-size: 30px;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);\n"
"background-image: url(design/assets/Backspace.png);")
        self.backspaceButton.setText("")
        self.backspaceButton.setObjectName("backspaceButton")
        emailMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(emailMainWindow)
        QtCore.QMetaObject.connectSlotsByName(emailMainWindow)

    def retranslateUi(self, emailMainWindow):
        _translate = QtCore.QCoreApplication.translate
        emailMainWindow.setWindowTitle(_translate("emailMainWindow", "MainWindow"))
        self.pushButton.setText(_translate("emailMainWindow", "1"))
        self.pushButton_2.setText(_translate("emailMainWindow", "2"))
        self.pushButton_3.setText(_translate("emailMainWindow", "3"))
        self.pushButton_4.setText(_translate("emailMainWindow", "4"))
        self.pushButton_5.setText(_translate("emailMainWindow", "5"))
        self.pushButton_6.setText(_translate("emailMainWindow", "0"))
        self.pushButton_7.setText(_translate("emailMainWindow", "6"))
        self.pushButton_8.setText(_translate("emailMainWindow", "9"))
        self.pushButton_9.setText(_translate("emailMainWindow", "7"))
        self.pushButton_10.setText(_translate("emailMainWindow", "8"))
        self.pushButton_11.setText(_translate("emailMainWindow", "q"))
        self.pushButton_12.setText(_translate("emailMainWindow", "w"))
        self.pushButton_13.setText(_translate("emailMainWindow", "e"))
        self.pushButton_14.setText(_translate("emailMainWindow", "r"))
        self.pushButton_15.setText(_translate("emailMainWindow", "t"))
        self.pushButton_16.setText(_translate("emailMainWindow", "y"))
        self.pushButton_17.setText(_translate("emailMainWindow", "p"))
        self.pushButton_18.setText(_translate("emailMainWindow", "o"))
        self.pushButton_19.setText(_translate("emailMainWindow", "-"))
        self.pushButton_21.setText(_translate("emailMainWindow", "u"))
        self.pushButton_22.setText(_translate("emailMainWindow", "i"))
        self.pushButton_23.setText(_translate("emailMainWindow", "f"))
        self.pushButton_24.setText(_translate("emailMainWindow", "d"))
        self.pushButton_25.setText(_translate("emailMainWindow", "l"))
        self.pushButton_26.setText(_translate("emailMainWindow", "_"))
        self.pushButton_27.setText(_translate("emailMainWindow", "k"))
        self.pushButton_28.setText(_translate("emailMainWindow", "g"))
        self.pushButton_29.setText(_translate("emailMainWindow", "a"))
        self.pushButton_30.setText(_translate("emailMainWindow", "h"))
        self.pushButton_31.setText(_translate("emailMainWindow", "j"))
        self.pushButton_32.setText(_translate("emailMainWindow", "s"))
        self.pushButton_20.setText(_translate("emailMainWindow", "v"))
        self.pushButton_33.setText(_translate("emailMainWindow", "c"))
        self.pushButton_34.setText(_translate("emailMainWindow", "."))
        self.pushButton_35.setText(_translate("emailMainWindow", "@"))
        self.pushButton_36.setText(_translate("emailMainWindow", "b"))
        self.pushButton_37.setText(_translate("emailMainWindow", "m"))
        self.pushButton_38.setText(_translate("emailMainWindow", "n"))
        self.pushButton_39.setText(_translate("emailMainWindow", "z"))
        self.pushButton_40.setText(_translate("emailMainWindow", "x"))
