# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'End.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EndMainWindow(object):
    def setupUi(self, EndMainWindow):
        EndMainWindow.setObjectName("EndMainWindow")
        EndMainWindow.resize(1080, 1920)
        self.centralwidget = QtWidgets.QWidget(EndMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.endBackground = QtWidgets.QLabel(self.centralwidget)
        self.endBackground.setGeometry(QtCore.QRect(0, 0, 1080, 1920))
        self.endBackground.setText("")
        self.endBackground.setPixmap(QtGui.QPixmap("design/assets/EndBackground.png"))
        self.endBackground.setObjectName("endBackground")
        self.endButton = QtWidgets.QPushButton(self.centralwidget)
        self.endButton.setGeometry(QtCore.QRect(347, 1215, 386, 108))
        self.endButton.setStyleSheet("background-image: url(design/assets/EndButton.png);\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.endButton.setText("")
        self.endButton.setObjectName("endButton")
        EndMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(EndMainWindow)
        QtCore.QMetaObject.connectSlotsByName(EndMainWindow)

    def retranslateUi(self, EndMainWindow):
        _translate = QtCore.QCoreApplication.translate
        EndMainWindow.setWindowTitle(_translate("EndMainWindow", "MainWindow"))
