# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Instruction.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InstructionMainWindow(object):
    def setupUi(self, InstructionMainWindow):
        InstructionMainWindow.setObjectName("InstructionMainWindow")
        InstructionMainWindow.resize(1080, 1920)
        self.centralwidget = QtWidgets.QWidget(InstructionMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.instructionBackground = QtWidgets.QLabel(self.centralwidget)
        self.instructionBackground.setGeometry(QtCore.QRect(0, 0, 1080, 1920))
        self.instructionBackground.setText("")
        self.instructionBackground.setPixmap(QtGui.QPixmap("design/assets/InstructionBackground.png"))
        self.instructionBackground.setObjectName("instructionBackground")
        self.instructionButton = QtWidgets.QPushButton(self.centralwidget)
        self.instructionButton.setGeometry(QtCore.QRect(294, 1671, 490, 108))
        self.instructionButton.setStyleSheet("background-image: url(design/assets/InstructionButton.png);\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.instructionButton.setText("")
        self.instructionButton.setObjectName("instructionButton")
        InstructionMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InstructionMainWindow)
        QtCore.QMetaObject.connectSlotsByName(InstructionMainWindow)

    def retranslateUi(self, InstructionMainWindow):
        _translate = QtCore.QCoreApplication.translate
        InstructionMainWindow.setWindowTitle(_translate("InstructionMainWindow", "MainWindow"))
