# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Player.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_videoplayerMainWindow(object):
    def setupUi(self, videoplayerMainWindow):
        videoplayerMainWindow.setObjectName("videoplayerMainWindow")
        videoplayerMainWindow.resize(1080, 1920)
        self.centralwidget = QtWidgets.QWidget(videoplayerMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(0, 0, 1080, 1920))
        self.videoLabel.setStyleSheet("background-color: #30363A")
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.headerLabel = QtWidgets.QLabel(self.centralwidget)
        self.headerLabel.setGeometry(QtCore.QRect(0, 0, 1080, 189))
        self.headerLabel.setPixmap(QtGui.QPixmap("design/assets/Header.png"))
        self.headerLabel.setObjectName("headerLabel")
        self.footerLabel = QtWidgets.QLabel(self.centralwidget)
        self.footerLabel.setGeometry(QtCore.QRect(0, 1810, 1080, 110))
        self.footerLabel.setPixmap(QtGui.QPixmap("design/assets/Footer3.png"))
        self.footerLabel.setObjectName("footerLabel")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(720, 1810, 360, 108))
        self.sendButton.setStyleSheet("background-image: url(design/assets/SendButton.png);\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.sendButton.setText("")
        self.sendButton.setObjectName("sendButton")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(360, 1810, 360, 108))
        self.playButton.setStyleSheet("background-image: url(design/assets/PlayButton.png);\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.playButton.setText("")
        self.playButton.setObjectName("playButton")
        self.recordButton = QtWidgets.QPushButton(self.centralwidget)
        self.recordButton.setGeometry(QtCore.QRect(0, 1810, 360, 108))
        self.recordButton.setStyleSheet("background-image: url(design/assets/RerecordButton.png);\n"
"border-style: outset;\n"
"border-width: 0px;\n"
"border-color: rgba(0,0,0,0);")
        self.recordButton.setText("")
        self.recordButton.setObjectName("recordButton")
        videoplayerMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(videoplayerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(videoplayerMainWindow)

    def retranslateUi(self, videoplayerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        videoplayerMainWindow.setWindowTitle(_translate("videoplayerMainWindow", "MainWindow"))
