# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Video.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoMainWindow(object):
    def setupUi(self, VideoMainWindow):
        VideoMainWindow.setObjectName("VideoMainWindow")
        VideoMainWindow.resize(1080, 1920)
        self.centralwidget = QtWidgets.QWidget(VideoMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(0, 0, 1080, 1920))
        self.videoLabel.setStyleSheet("background-color: #30363A")
        self.videoLabel.setText("")
        self.videoLabel.setObjectName("videoLabel")
        self.headerLabel = QtWidgets.QLabel(self.centralwidget)
        self.headerLabel.setGeometry(QtCore.QRect(0, 0, 1080, 189))
        self.headerLabel.setPixmap(QtGui.QPixmap("design/assets/Header.png"))
        self.headerLabel.setObjectName("headerLabel")
        self.footerLabel = QtWidgets.QLabel(self.centralwidget)
        self.footerLabel.setGeometry(QtCore.QRect(0, 1780, 1080, 140))
        self.footerLabel.setPixmap(QtGui.QPixmap("design/assets/Footer.png"))
        self.footerLabel.setObjectName("footerLabel")
        self.prepareLabel = QtWidgets.QLabel(self.centralwidget)
        self.prepareLabel.setGeometry(QtCore.QRect(181, 981, 718, 174))
        self.prepareLabel.setPixmap(QtGui.QPixmap("design/assets/PrepareLabel.png"))
        self.prepareLabel.setObjectName("prepareLabel")
        self.secondsLabel = QtWidgets.QLabel(self.centralwidget)
        self.secondsLabel.setGeometry(QtCore.QRect(540, 1812, 540, 108))
        self.secondsLabel.setTextFormat(QtCore.Qt.AutoText)
        self.secondsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.secondsLabel.setObjectName("secondsLabel")
        self.comandLabel = QtWidgets.QLabel(self.centralwidget)
        self.comandLabel.setGeometry(QtCore.QRect(0, 1812, 540, 108))
        self.comandLabel.setTextFormat(QtCore.Qt.AutoText)
        self.comandLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.comandLabel.setObjectName("comandLabel")
        VideoMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(VideoMainWindow)
        QtCore.QMetaObject.connectSlotsByName(VideoMainWindow)

    def retranslateUi(self, VideoMainWindow):
        _translate = QtCore.QCoreApplication.translate
        VideoMainWindow.setWindowTitle(_translate("VideoMainWindow", "MainWindow"))
        self.secondsLabel.setText(_translate("VideoMainWindow", "5 sec"))
        self.comandLabel.setText(_translate("VideoMainWindow", "Приготовься..."))
